library(shiny)
library(shinydashboard)
library(shinyjs)
library(DT)
library(ggplot2)
library(ggrepel)
library(reshape2)
library(pastecs)
library(rmarkdown)
library(knitr)
library(shinythemes)
library(Metrics)
library(caret)
library(car)
library(MASS)
library(shinyWidgets)
library(ggthemes)
library(ggExtra)
library(olsrr)
library(ggplot2)
library(shiny)
library(devtools)
library(reshape)
library(psych)
library(lsr)
library(archetypes)
library(GGally)
library(ade4)
library(reshape2)
library(plotly)
library (DescTools)


source("helpers.R", local=FALSE) # Load all the code needed to show feedback on a button click
source("BenchmarkClassesFnct.R", local=FALSE)

